included:
  - Sources
  - Tests
  - Example
  - Package.swift
excluded:
  - .build
  - .docarchives
  - Sources/SwiftAssRenderer/Docs
type_body_length:
  - 500
  - 1000
file_length:
  warning: 1000
  error: 2000
large_tuple:
  warning: 5
  error: 10
